version: 2

models:
  - name: load_data
    description: "A starter dbt model"
    columns:
      - name: CUST_ID
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null

  - name: alter_data
    description: "A starter dbt model"
    columns:
      - name: CUST_ID
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null

  - name: delete_data
    description: "A starter dbt model"
    columns:
      - name: CUST_ID
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null

        
  - name: final_data
    description: "A starter dbt model"
    columns:
      - name: CUST_ID
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null




sources:
  - name: data
    database: dbt_db 
    schema: raw 
    tables:
      - name: RAW_DATA
      

    
          
