version: 2

models:
  - name: load_data
    description: "A starter dbt model"
    columns:
      - name: CUST_ID
        description: This is a unique identifier for a customer
        # tests:
        #   - unique
         

  - name: alter_data
    description: "A starter dbt model"
    columns:
      - name: CUST_ID
        description: This is a unique identifier for a customer
        # tests:
        #   - unique
          

  - name: delete_data
    description: "A starter dbt model"
    columns:
      - name: CUST_ID
        description: This is a unique identifier for a customer
        # tests:
        #   - unique
          

        
  - name: final_data
    description: "A starter dbt model"
    columns:
      - name: CUST_ID
        description: This is a unique identifier for a customer
        # tests:
        #   - unique
         




sources:
  - name: data
    database: dbt_db 
    schema: raw 
    tables:
      - name: RAW_DATA
      

    
          
